"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lyrics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=300), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('artist', sa.String(length=300), nullable=False),
    sa.Column('album', sa.String(length=300), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('lyrics_offset', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('library', 'import_', 'upload', name='songsource', native_enum=False, length=16), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('lyrics_status', sa.Enum('pending', 'found', 'needs_choice', 'not_found', name='lyricsstatus', native_enum=False, length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_table('lyrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('lrclib', 'sidecar', 'upload', name='lyricssource', native_enum=False, length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lyrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lyrics_song_id'), ['song_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('lyrics_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lyrics_id'], ['lyrics.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_lyrics_id'), ['lyrics_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_song_id'), ['song_id'], unique=False)

    op.create_table('lyric_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lyrics_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lyrics_id'], ['lyrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lyrics_id', 'sequence')
    )
    with op.batch_alter_table('lyric_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lyric_lines_lyrics_id'), ['lyrics_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('lyrics_id', sa.Integer(), nullable=False),
    sa.Column('lyric_line_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('missing_word', sa.String(length=100), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('audio_start', sa.Float(), nullable=True),
    sa.Column('audio_end', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lyric_line_id'], ['lyric_lines.id'], ),
    sa.ForeignKeyConstraint(['lyrics_id'], ['lyrics.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lyrics_id', 'difficulty', 'lyric_line_id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_lyric_line_id'), ['lyric_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_lyrics_id'), ['lyrics_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_song_id'), ['song_id'], unique=False)

    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'position')
    )
    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    op.create_table('game_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'question_id')
    )
    with op.batch_alter_table('game_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_answers_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('game_answers')

    op.drop_table('question_options')

    op.drop_table('questions')

    op.drop_table('lyric_lines')

    op.drop_table('games')

    op.drop_table('lyrics')
    op.drop_table('songs')
    op.drop_table('lyrics_cache')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
